//next and fonts
import type { Metadata } from "next";
import { Ubuntu} from "next/font/google";

//css
import "./globals.css";

//pages
import Home from "./pages/home/page";

//components
import Navbar from "./components/Navbar";


const ubuntu = Ubuntu({
  weight: '400',
  subsets: ['latin'],
})

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ubuntu.className}>
      <body>
        <header className="relative z-50 bg-(--background) flex">
          <Navbar />
        </header>

        <section className="relative z-50">
          <Home/>
        </section>

        <main className="relative z-10">
          {children}
        </main>

      </body>
    </html>
  );
}
